/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;
import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.dao.TelefonoDao;
import ec.edu.ups.modelo.Telefono;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dutan2000
 */
public class VentanaSecundaria extends javax.swing.JFrame {
    NuevoMenuPrincipal menuPrincipal;
    TelefonoVista telefonoLista;
    ControladorTelefono cntrlTelefono;
    
    
    
    public void limpiar(){
        txtCodigo.setText("");
        txtNumTel.setText("");
        txtTipoTele.setText("");
        txtOperadora.setText("");
    }
    /**
     * Creates new form VentanaSecundaria
     */
    public VentanaSecundaria(NuevoMenuPrincipal menuP,ControladorTelefono tlf) {
        menuPrincipal=menuP;
        cntrlTelefono=tlf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTRegistrar = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNumTel = new javax.swing.JTextField();
        lBorrar = new javax.swing.JLabel();
        txtTipoTele = new javax.swing.JTextField();
        lModificar = new javax.swing.JLabel();
        txtOperadora = new javax.swing.JTextField();
        lBuscarT = new javax.swing.JLabel();
        BotonDAO = new javax.swing.JButton();
        botonListarTele = new javax.swing.JButton();
        botonSalirVentanaSecundaria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTRegistrar.setText("Ingrese codigo del Telefono");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lBorrar.setText("Ingrese #codigo de telefono");

        txtTipoTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoTeleActionPerformed(evt);
            }
        });

        lModificar.setText("Ingrese que tipo de telefono pertenece el #");

        lBuscarT.setText("Operadora");

        BotonDAO.setText("Ingresar");
        BotonDAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDAOActionPerformed(evt);
            }
        });

        botonListarTele.setText("Lista Telefonos");
        botonListarTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarTeleActionPerformed(evt);
            }
        });

        botonSalirVentanaSecundaria.setText("Salir");
        botonSalirVentanaSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirVentanaSecundariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BotonDAO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonListarTele))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTipoTele, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lTRegistrar)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lBorrar)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(lBuscarT))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(botonSalirVentanaSecundaria)))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lTRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonDAO)
                    .addComponent(botonListarTele))
                .addGap(18, 18, 18)
                .addComponent(botonSalirVentanaSecundaria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDAOActionPerformed
        int codigo=Integer.parseInt(txtCodigo.getText());
        String numero = txtNumTel.getText();
        String tipo=txtTipoTele.getText();
        String operadora=txtOperadora.getText();
        Telefono telefono=new Telefono(codigo, numero, tipo, operadora);
        
        cntrlTelefono.registrar(telefono);
                
        
        JOptionPane.showMessageDialog(null, "Telefono registrado");
        limpiar();
        
        //System.out.println(cntrlTelefono.verTelefonos());


    }//GEN-LAST:event_BotonDAOActionPerformed

    private void botonListarTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarTeleActionPerformed
    if(telefonoLista==null){
        telefonoLista=new TelefonoVista(this, cntrlTelefono); 
    }
    
    telefonoLista.setVisible(true);
    telefonoLista.listar();
    this.setVisible(false);
    
    }//GEN-LAST:event_botonListarTeleActionPerformed

    private void botonSalirVentanaSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirVentanaSecundariaActionPerformed
        menuPrincipal.setVisible(true);
        this.setVisible(false);
        



    }//GEN-LAST:event_botonSalirVentanaSecundariaActionPerformed

    private void txtTipoTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoTeleActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDAO;
    private javax.swing.JButton botonListarTele;
    private javax.swing.JButton botonSalirVentanaSecundaria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lBorrar;
    private javax.swing.JLabel lBuscarT;
    private javax.swing.JLabel lModificar;
    private javax.swing.JLabel lTRegistrar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNumTel;
    private javax.swing.JTextField txtOperadora;
    private javax.swing.JTextField txtTipoTele;
    // End of variables declaration//GEN-END:variables
}
